### ISSUE TITLE
Confirm the meaning of "DeltaPhi" log

### ISSUE THREAD

**Issue by EvanBianco** [brendonhall/facies_classification#3]
Forgive me if this is old-hat to you, but the "DeltaPhi" logs reminds me of an "HDRA" or "DRHO" type log or a Density _correction_ log: not strictly density. This so called density correction log is often an indicator of hole quality and can often be seen deviate significantly from zero when there is hole washout.

Shrimplin log called DeltaPhi looks to be bonafide "porosity values", but the same curve for Shankle looks to me like it is a Density Correction log. 

Logs! Grumble Grumble Grumble. Is there any meta data you can use to get to the bottom of this?

**Comment by kwinkunks** [comment]
This is basically a packaged dataset, so we can't poke into it all that much, but on the plus side it's been QC'd a bit.

According to the original KU exercise, it is delta-phi, or density-neutron porosity difference. It's a valid lithology indicator.
