### ISSUE TITLE
Cosmetic configurations to log plots

### ISSUE THREAD

**Issue by EvanBianco** [brendonhall/facies_classification#4]
You may very well decide to keep each log in a track of its own, but allow me to suggest what I think to be is a more standard view of a typical suite of petrophysical logs (image).

Two elements to draw your attention to. The curve order and stylings, and the x-scale ranges. Specifically, the shading between the neutron porosity and density porosity show the "shaliness" (in grey) and the classic "gas response" in red when the curves cross over.

I've been meaning to generalize this as a sort of template display in `welly`, but because of the myriad combinations of curves, I haven't quite gotten around to it yet. 

![image](https://cloud.githubusercontent.com/assets/1699959/17330284/ac1b2fd6-589c-11e6-8872-aaa5342969db.png)

Perhaps I will have a go at this this week. This is more cosmetic than anything.

**Comment by kwinkunks** [comment]
Since this is more of a machine learning treatment than a petrophysical treatment, I think it's OK to handle the data more as 'pure' vectors, especially given that fiddling with mpl is one of the scientific world's greatest timesucks :)
